# Google App Engine configuration (optional)
runtime: python311

instance_class: F4

entrypoint: streamlit run app/streamlit_app.py --server.port=8080 --server.address=0.0.0.0

env_variables:
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
