from setuptools import setup, find_packages

setup(
    name="deepfake-detector",
    version="1.0.0",
    description="Production-ready deepfake video detection system",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "torch>=2.1.0",
        "torchvision>=0.16.0",
        "opencv-python>=4.8.1",
        "mediapipe>=0.10.8",
        "facenet-pytorch>=2.5.3",
        "librosa>=0.10.1",
        "scipy>=1.11.4",
        "timm>=0.9.12",
        "scikit-learn>=1.3.2",
        "pandas>=2.1.4",
        "numpy>=1.24.3",
        "matplotlib>=3.8.2",
        "streamlit>=1.28.2",
        "plotly>=5.18.0",
        "tqdm>=4.66.1",
        "pillow>=10.1.0",
        "pyyaml>=6.0.1",
        "albumentations>=1.3.1",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)
