data:
  video_resolution: [224, 224]
  frame_rate: 30
  num_frames: 20
  batch_size: 4
  num_workers: 4

model:
  backbone: "efficientnet_b4"
  pretrained: true
  num_classes: 2
  dropout: 0.4
  hidden_dim: 768

training:
  epochs: 100
  learning_rate: 0.0003
  min_learning_rate: 0.000001
  weight_decay: 0.00001
  early_stopping_patience: 15
  warmup_epochs: 5
  label_smoothing: 0.1
  mixup_alpha: 0.2
  gradient_clip: 1.0
  use_cosine_schedule: true

detection:
  confidence_threshold: 0.65
